version: '3.4'

services:
  fastdeliveruu.api:
    image: ${DOCKER_REGISTRY-}fastdeliveruuapi
    build:
      context: .
      dockerfile: src/FastDeliveruu.Api/Dockerfile
    container_name: fastdeliveruu.api
    ports:
      - 5000:5000
      - 5001:5001
    networks:
      - fastdeliveruu-network

  fastdeliveruu.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: fastdeliveruu.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123456
      - MSSQL_PID=Express
    volumes:
      - ./.containers/fastdeliveruu-db:/var/opt/mssql/data
    ports:
      - 1433:1433    
    networks:
      - fastdeliveruu-network

  fastdeliveruu.cache:
    image: redis:latest
    container_name: fastdeliveruu.cache
    restart: always
    volumes:
      - ./.containers/fastdeliveruu-cache:/data
    ports:
      - 6379:6379
    networks:
      - fastdeliveruu-network

networks:
  fastdeliveruu-network:
    driver: bridge
