FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 5233

ENV ASPNETCORE_URLS=http://+:5233

# # Creates a non-root user with an explicit UID and adds permission to access the /app folder
# # For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
# RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
# USER appuser

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["src/FastDeliveruu.Api/FastDeliveruu.Api.csproj", "src/FastDeliveruu.Api/"]
RUN dotnet restore "src/FastDeliveruu.Api/FastDeliveruu.Api.csproj"
COPY . .
WORKDIR "/src/src/FastDeliveruu.Api"
RUN dotnet build "FastDeliveruu.Api.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "FastDeliveruu.Api.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FastDeliveruu.Api.dll"]
